# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from distributed_inference.proto import inference_pb2 as inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """============================================================
    Node Service — runs on each node
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModelShard = channel.unary_unary(
                '/distributed_inference.NodeService/LoadModelShard',
                request_serializer=inference__pb2.ShardAssignment.SerializeToString,
                response_deserializer=inference__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.RunForward = channel.unary_unary(
                '/distributed_inference.NodeService/RunForward',
                request_serializer=inference__pb2.ActivationData.SerializeToString,
                response_deserializer=inference__pb2.ActivationData.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/distributed_inference.NodeService/Heartbeat',
                request_serializer=inference__pb2.Empty.SerializeToString,
                response_deserializer=inference__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.UnloadShard = channel.unary_unary(
                '/distributed_inference.NodeService/UnloadShard',
                request_serializer=inference__pb2.Empty.SerializeToString,
                response_deserializer=inference__pb2.NodeStatus.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """============================================================
    Node Service — runs on each node
    ============================================================
    """

    def LoadModelShard(self, request, context):
        """Coordinator tells node to load specific model layers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunForward(self, request, context):
        """Forward pass: receive activations, process through local layers, return activations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadShard(self, request, context):
        """Unload current shard (for re-partitioning)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModelShard': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModelShard,
                    request_deserializer=inference__pb2.ShardAssignment.FromString,
                    response_serializer=inference__pb2.NodeStatus.SerializeToString,
            ),
            'RunForward': grpc.unary_unary_rpc_method_handler(
                    servicer.RunForward,
                    request_deserializer=inference__pb2.ActivationData.FromString,
                    response_serializer=inference__pb2.ActivationData.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=inference__pb2.Empty.FromString,
                    response_serializer=inference__pb2.HeartbeatResponse.SerializeToString,
            ),
            'UnloadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadShard,
                    request_deserializer=inference__pb2.Empty.FromString,
                    response_serializer=inference__pb2.NodeStatus.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_inference.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_inference.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """============================================================
    Node Service — runs on each node
    ============================================================
    """

    @staticmethod
    def LoadModelShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/LoadModelShard',
            inference__pb2.ShardAssignment.SerializeToString,
            inference__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/RunForward',
            inference__pb2.ActivationData.SerializeToString,
            inference__pb2.ActivationData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/Heartbeat',
            inference__pb2.Empty.SerializeToString,
            inference__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/UnloadShard',
            inference__pb2.Empty.SerializeToString,
            inference__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorServiceStub(object):
    """============================================================
    Coordinator Service — runs on the coordinator
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/distributed_inference.CoordinatorService/RegisterNode',
                request_serializer=inference__pb2.NodeInfo.SerializeToString,
                response_deserializer=inference__pb2.RegistrationAck.FromString,
                _registered_method=True)
        self.ReportHealth = channel.unary_unary(
                '/distributed_inference.CoordinatorService/ReportHealth',
                request_serializer=inference__pb2.NodeStatus.SerializeToString,
                response_deserializer=inference__pb2.Empty.FromString,
                _registered_method=True)
        self.SubmitInference = channel.unary_unary(
                '/distributed_inference.CoordinatorService/SubmitInference',
                request_serializer=inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=inference__pb2.InferenceResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """============================================================
    Coordinator Service — runs on the coordinator
    ============================================================
    """

    def RegisterNode(self, request, context):
        """Node registers itself with the coordinator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportHealth(self, request, context):
        """Node sends periodic health reports
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitInference(self, request, context):
        """Client submits an inference request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=inference__pb2.NodeInfo.FromString,
                    response_serializer=inference__pb2.RegistrationAck.SerializeToString,
            ),
            'ReportHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportHealth,
                    request_deserializer=inference__pb2.NodeStatus.FromString,
                    response_serializer=inference__pb2.Empty.SerializeToString,
            ),
            'SubmitInference': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitInference,
                    request_deserializer=inference__pb2.InferenceRequest.FromString,
                    response_serializer=inference__pb2.InferenceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_inference.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_inference.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """============================================================
    Coordinator Service — runs on the coordinator
    ============================================================
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.CoordinatorService/RegisterNode',
            inference__pb2.NodeInfo.SerializeToString,
            inference__pb2.RegistrationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.CoordinatorService/ReportHealth',
            inference__pb2.NodeStatus.SerializeToString,
            inference__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.CoordinatorService/SubmitInference',
            inference__pb2.InferenceRequest.SerializeToString,
            inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
