# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from distributed_inference.proto import inference_pb2 as proto_dot_inference__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/inference_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeServiceStub(object):
    """============================================================
    Node Service — runs on each node
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LoadModelShard = channel.unary_unary(
                '/distributed_inference.NodeService/LoadModelShard',
                request_serializer=proto_dot_inference__pb2.ShardAssignment.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.RunForward = channel.unary_unary(
                '/distributed_inference.NodeService/RunForward',
                request_serializer=proto_dot_inference__pb2.ActivationData.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.ActivationData.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/distributed_inference.NodeService/Heartbeat',
                request_serializer=proto_dot_inference__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.UnloadShard = channel.unary_unary(
                '/distributed_inference.NodeService/UnloadShard',
                request_serializer=proto_dot_inference__pb2.Empty.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.NodeStatus.FromString,
                _registered_method=True)
        self.ClearRequestCache = channel.unary_unary(
                '/distributed_inference.NodeService/ClearRequestCache',
                request_serializer=proto_dot_inference__pb2.CacheControl.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.Empty.FromString,
                _registered_method=True)
        self.CancelRequest = channel.unary_unary(
                '/distributed_inference.NodeService/CancelRequest',
                request_serializer=proto_dot_inference__pb2.CacheControl.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.Empty.FromString,
                _registered_method=True)


class NodeServiceServicer(object):
    """============================================================
    Node Service — runs on each node
    ============================================================
    """

    def LoadModelShard(self, request, context):
        """Coordinator tells node to load specific model layers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunForward(self, request, context):
        """Forward pass: receive activations, process through local layers, return activations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UnloadShard(self, request, context):
        """Unload current shard (for re-partitioning)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearRequestCache(self, request, context):
        """Clear cache state for a specific request or all requests.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRequest(self, request, context):
        """Cancel an in-flight request on this node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LoadModelShard': grpc.unary_unary_rpc_method_handler(
                    servicer.LoadModelShard,
                    request_deserializer=proto_dot_inference__pb2.ShardAssignment.FromString,
                    response_serializer=proto_dot_inference__pb2.NodeStatus.SerializeToString,
            ),
            'RunForward': grpc.unary_unary_rpc_method_handler(
                    servicer.RunForward,
                    request_deserializer=proto_dot_inference__pb2.ActivationData.FromString,
                    response_serializer=proto_dot_inference__pb2.ActivationData.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=proto_dot_inference__pb2.Empty.FromString,
                    response_serializer=proto_dot_inference__pb2.HeartbeatResponse.SerializeToString,
            ),
            'UnloadShard': grpc.unary_unary_rpc_method_handler(
                    servicer.UnloadShard,
                    request_deserializer=proto_dot_inference__pb2.Empty.FromString,
                    response_serializer=proto_dot_inference__pb2.NodeStatus.SerializeToString,
            ),
            'ClearRequestCache': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearRequestCache,
                    request_deserializer=proto_dot_inference__pb2.CacheControl.FromString,
                    response_serializer=proto_dot_inference__pb2.Empty.SerializeToString,
            ),
            'CancelRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRequest,
                    request_deserializer=proto_dot_inference__pb2.CacheControl.FromString,
                    response_serializer=proto_dot_inference__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_inference.NodeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_inference.NodeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeService(object):
    """============================================================
    Node Service — runs on each node
    ============================================================
    """

    @staticmethod
    def LoadModelShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/LoadModelShard',
            proto_dot_inference__pb2.ShardAssignment.SerializeToString,
            proto_dot_inference__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RunForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/RunForward',
            proto_dot_inference__pb2.ActivationData.SerializeToString,
            proto_dot_inference__pb2.ActivationData.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/Heartbeat',
            proto_dot_inference__pb2.Empty.SerializeToString,
            proto_dot_inference__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UnloadShard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/UnloadShard',
            proto_dot_inference__pb2.Empty.SerializeToString,
            proto_dot_inference__pb2.NodeStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearRequestCache(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/ClearRequestCache',
            proto_dot_inference__pb2.CacheControl.SerializeToString,
            proto_dot_inference__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.NodeService/CancelRequest',
            proto_dot_inference__pb2.CacheControl.SerializeToString,
            proto_dot_inference__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CoordinatorServiceStub(object):
    """============================================================
    Coordinator Service — runs on the coordinator
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterNode = channel.unary_unary(
                '/distributed_inference.CoordinatorService/RegisterNode',
                request_serializer=proto_dot_inference__pb2.NodeInfo.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.RegistrationAck.FromString,
                _registered_method=True)
        self.ReportHealth = channel.unary_unary(
                '/distributed_inference.CoordinatorService/ReportHealth',
                request_serializer=proto_dot_inference__pb2.NodeStatus.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.Empty.FromString,
                _registered_method=True)
        self.SubmitInference = channel.unary_unary(
                '/distributed_inference.CoordinatorService/SubmitInference',
                request_serializer=proto_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.InferenceResponse.FromString,
                _registered_method=True)
        self.SubmitInferenceStream = channel.unary_stream(
                '/distributed_inference.CoordinatorService/SubmitInferenceStream',
                request_serializer=proto_dot_inference__pb2.InferenceRequest.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.InferenceEvent.FromString,
                _registered_method=True)
        self.CancelInference = channel.unary_unary(
                '/distributed_inference.CoordinatorService/CancelInference',
                request_serializer=proto_dot_inference__pb2.CancelInferenceRequest.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.CancelInferenceResponse.FromString,
                _registered_method=True)
        self.SwitchModel = channel.unary_unary(
                '/distributed_inference.CoordinatorService/SwitchModel',
                request_serializer=proto_dot_inference__pb2.SwitchModelRequest.SerializeToString,
                response_deserializer=proto_dot_inference__pb2.SwitchModelResponse.FromString,
                _registered_method=True)


class CoordinatorServiceServicer(object):
    """============================================================
    Coordinator Service — runs on the coordinator
    ============================================================
    """

    def RegisterNode(self, request, context):
        """Node registers itself with the coordinator
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportHealth(self, request, context):
        """Node sends periodic health reports
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitInference(self, request, context):
        """Client submits an inference request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitInferenceStream(self, request, context):
        """Client submits an inference request and receives streaming events.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelInference(self, request, context):
        """Client requests cancellation of an in-flight inference request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SwitchModel(self, request, context):
        """Client requests the cluster to dynamically switch models
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CoordinatorServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=proto_dot_inference__pb2.NodeInfo.FromString,
                    response_serializer=proto_dot_inference__pb2.RegistrationAck.SerializeToString,
            ),
            'ReportHealth': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportHealth,
                    request_deserializer=proto_dot_inference__pb2.NodeStatus.FromString,
                    response_serializer=proto_dot_inference__pb2.Empty.SerializeToString,
            ),
            'SubmitInference': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitInference,
                    request_deserializer=proto_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=proto_dot_inference__pb2.InferenceResponse.SerializeToString,
            ),
            'SubmitInferenceStream': grpc.unary_stream_rpc_method_handler(
                    servicer.SubmitInferenceStream,
                    request_deserializer=proto_dot_inference__pb2.InferenceRequest.FromString,
                    response_serializer=proto_dot_inference__pb2.InferenceEvent.SerializeToString,
            ),
            'CancelInference': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelInference,
                    request_deserializer=proto_dot_inference__pb2.CancelInferenceRequest.FromString,
                    response_serializer=proto_dot_inference__pb2.CancelInferenceResponse.SerializeToString,
            ),
            'SwitchModel': grpc.unary_unary_rpc_method_handler(
                    servicer.SwitchModel,
                    request_deserializer=proto_dot_inference__pb2.SwitchModelRequest.FromString,
                    response_serializer=proto_dot_inference__pb2.SwitchModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'distributed_inference.CoordinatorService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('distributed_inference.CoordinatorService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CoordinatorService(object):
    """============================================================
    Coordinator Service — runs on the coordinator
    ============================================================
    """

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.CoordinatorService/RegisterNode',
            proto_dot_inference__pb2.NodeInfo.SerializeToString,
            proto_dot_inference__pb2.RegistrationAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.CoordinatorService/ReportHealth',
            proto_dot_inference__pb2.NodeStatus.SerializeToString,
            proto_dot_inference__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.CoordinatorService/SubmitInference',
            proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            proto_dot_inference__pb2.InferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitInferenceStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/distributed_inference.CoordinatorService/SubmitInferenceStream',
            proto_dot_inference__pb2.InferenceRequest.SerializeToString,
            proto_dot_inference__pb2.InferenceEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelInference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.CoordinatorService/CancelInference',
            proto_dot_inference__pb2.CancelInferenceRequest.SerializeToString,
            proto_dot_inference__pb2.CancelInferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SwitchModel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/distributed_inference.CoordinatorService/SwitchModel',
            proto_dot_inference__pb2.SwitchModelRequest.SerializeToString,
            proto_dot_inference__pb2.SwitchModelResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
